<?php

namespace App\Importing\Generator;

use InvalidArgumentException;
use Random\Engine\Mt19937;
use Random\Randomizer;
use RuntimeException;

/**
 * Streams a synthetic trade-statistics CSV to disk.
 *
 * Output is deterministic for a given seed (Mt19937 is stable across PHP
 * versions), so benchmark and test inputs can be regenerated byte for byte.
 * Rows are buffered in small batches and flushed, so memory stays flat no
 * matter how many rows are requested.
 */
final class TradeCsvGenerator
{
    public const array HEADER = ['time_ref', 'account', 'code', 'country_code', 'product_type', 'value', 'status'];

    private const array ACCOUNTS = ['Exports', 'Imports'];

    private const array PRODUCT_TYPES = ['Goods', 'Services'];

    private const array STATUSES = ['F', 'P', 'R'];

    private const array COUNTRIES = [
        'AE', 'AR', 'AU', 'BE', 'BR', 'CA', 'CH', 'CL', 'CN', 'DE', 'DK', 'ES', 'FI', 'FJ', 'FR', 'GB',
        'HK', 'ID', 'IE', 'IN', 'IT', 'JP', 'KR', 'MX', 'MY', 'NL', 'NO', 'NZ', 'PE', 'PG', 'PH', 'PL',
        'SA', 'SE', 'SG', 'TH', 'TO', 'TW', 'US', 'VN', 'WS', 'ZA',
    ];

    private const array SERVICE_CODES = ['A11', 'A12', 'A21', 'A22', 'A31', 'A32', 'B10', 'B20', 'C10', 'C20', 'D11', 'D12'];

    private const int FLUSH_EVERY = 5_000;

    public function __construct(private readonly int $seed = 42) {}

    /**
     * @param  float  $errorPercent  Percentage (0–100) of data rows to corrupt in a varied way.
     * @param  bool  $quotedNewlines  Also emit rows whose `code` field is a quoted multi-line value.
     *                                These rows are well-formed CSV but fail validation, so they count as invalid.
     */
    public function generate(string $path, int $rows, float $errorPercent = 0.0, bool $quotedNewlines = false): GeneratorResult
    {
        if ($rows < 0) {
            throw new InvalidArgumentException('Row count must not be negative.');
        }

        if ($errorPercent < 0 || $errorPercent > 100) {
            throw new InvalidArgumentException('Error percentage must be between 0 and 100.');
        }

        $random = new Randomizer(new Mt19937($this->seed));
        $handle = @fopen($path, 'wb');

        if ($handle === false) {
            throw new RuntimeException("Unable to open [{$path}] for writing.");
        }

        $badRowsWanted = (int) round($rows * $errorPercent / 100);
        $newlineRowsWanted = $quotedNewlines ? max(1, intdiv($rows, 100)) : 0;
        $newlineRowsWanted = min($newlineRowsWanted, $rows - $badRowsWanted);

        $badRowsLeft = $badRowsWanted;
        $newlineRowsLeft = $newlineRowsWanted;
        $kinds = [];
        $buffer = implode(',', self::HEADER)."\n";
        $buffered = 0;

        for ($i = 0; $i < $rows; $i++) {
            $remaining = $rows - $i;

            // Selection sampling (Knuth, Algorithm S): picks exactly the
            // requested number of rows, uniformly, in a single pass.
            if ($badRowsLeft > 0 && $random->getInt(1, $remaining) <= $badRowsLeft) {
                $badRowsLeft--;
                [$kind, $line] = $this->badRow($random);
                $kinds[$kind] = ($kinds[$kind] ?? 0) + 1;
            } elseif ($newlineRowsLeft > 0 && $random->getInt(1, $remaining - $badRowsLeft) <= $newlineRowsLeft) {
                $newlineRowsLeft--;
                $line = $this->quotedNewlineRow($random);
                $kinds['quoted_newline'] = ($kinds['quoted_newline'] ?? 0) + 1;
            } else {
                $line = $this->validRow($random, $quotedNewlines);
            }

            $buffer .= $line."\n";

            if (++$buffered === self::FLUSH_EVERY) {
                fwrite($handle, $buffer);
                $buffer = '';
                $buffered = 0;
            }
        }

        fwrite($handle, $buffer);
        fclose($handle);

        clearstatcache(true, $path);
        ksort($kinds);

        return new GeneratorResult(
            path: $path,
            rows: $rows,
            invalidRows: $badRowsWanted + $newlineRowsWanted,
            bytes: (int) filesize($path),
            invalidByKind: $kinds,
        );
    }

    /**
     * @return array{0: string, 1: string, 2: string, 3: string, 4: string, 5: string, 6: string}
     */
    private function validFields(Randomizer $random): array
    {
        $productType = self::PRODUCT_TYPES[$random->getInt(0, 1)];

        return [
            sprintf('%04d%02d', $random->getInt(2000, 2025), $random->getInt(1, 12)),
            self::ACCOUNTS[$random->getInt(0, 1)],
            $productType === 'Goods'
                ? sprintf('%02d', $random->getInt(1, 99))
                : self::SERVICE_CODES[$random->getInt(0, count(self::SERVICE_CODES) - 1)],
            self::COUNTRIES[$random->getInt(0, count(self::COUNTRIES) - 1)],
            $productType,
            sprintf('%d.%02d', $random->getInt(0, 99_999_999), $random->getInt(0, 99)),
            self::STATUSES[$random->getInt(0, 2)],
        ];
    }

    private function validRow(Randomizer $random, bool $withQuoting): string
    {
        $fields = $this->validFields($random);

        // When exercising the splitter, quote some ordinary fields too so
        // that valid rows contain enclosures as well.
        if ($withQuoting && $random->getInt(1, 20) === 1) {
            $fields[4] = '"'.$fields[4].'"';
        }

        return implode(',', $fields);
    }

    private function quotedNewlineRow(Randomizer $random): string
    {
        $fields = $this->validFields($random);
        $fields[2] = '"'.$fields[2]."\n".'line ""two"", with comma"';

        return implode(',', $fields);
    }

    /**
     * Each corruption breaks exactly one rule, so every bad row yields exactly one error.
     *
     * @return array{0: string, 1: string}
     */
    private function badRow(Randomizer $random): array
    {
        $fields = $this->validFields($random);
        $kind = $random->getInt(0, 8);

        switch ($kind) {
            case 0:
                array_pop($fields);

                return ['too_few_fields', implode(',', $fields)];
            case 1:
                $fields[] = 'extra';

                return ['too_many_fields', implode(',', $fields)];
            case 2:
                $fields[0] = substr($fields[0], 0, 4).'13';

                return ['bad_month', implode(',', $fields)];
            case 3:
                $fields[0] = substr($fields[0], 0, 4).'-'.substr($fields[0], 4);

                return ['bad_period_format', implode(',', $fields)];
            case 4:
                $fields[5] = 'N/A';

                return ['non_numeric_value', implode(',', $fields)];
            case 5:
                $fields[5] .= '5';

                return ['too_many_decimals', implode(',', $fields)];
            case 6:
                $fields[1] = 'Exprts';

                return ['bad_account', implode(',', $fields)];
            case 7:
                $fields[6] = 'X';

                return ['bad_status', implode(',', $fields)];
            default:
                $fields[3] = strtolower($fields[3]);

                return ['bad_country_code', implode(',', $fields)];
        }
    }
}
